### ISSUE TITLE
Is incomplete?

### ISSUE THREAD

**Issue by bnd170** [sinenco/AllopassPayment#1]
This repository is incomplete? How can i work with it?

**Comment by jordandegea** [comment]
AllopassPayment works with AllopassAPI. You have to set AllopassAPI. Try to see my AllopassAPI README. 
I work on many project. If you don't find, I will complete the documentation.

**Comment by bnd170** [comment]
Please do it, because i try to setup the bundle on my project and i don't understand how it works :/

Thanks a lot!

**Comment by sinenco** [comment]
I will work on it this week.

**Comment by jordandegea** [comment]
Hi, I wrote the README. All steps are explained. Say me if that's good.

**Comment by bnd170** [comment]
Can you put some example of payment?

**Comment by jordandegea** [comment]
I don't understand what you want ? Can you explain please ?

**Comment by bnd170** [comment]
Yes, an example to show the button for pay to user and how to get the
notification from allowpass

2015-09-24 15:17 GMT+02:00 Jordan DE GEA notifications@github.com:

**Comment by jordandegea** [comment]
Hi, I add steps for use it and a little description of the payment page.

**Comment by jordandegea** [comment]
Hi, Is the issue solved ?

**Comment by bnd170** [comment]
Yes dude. Thanks a lot. Your readme now looks fine. Hope it helps more ppl.

**Comment by jordandegea** [comment]
Hi, for information. Is the extension useful for you ?

**Comment by bnd170** [comment]
Yes :) Thanks and good job

2015-12-03 11:48 GMT+01:00 Jordan DE GEA notifications@github.com:
